"""Compile an Authority Manifest into AWS Cedar policies."""
from __future__ import annotations

from ..core.schema import Manifest


def compile_cedar(m: Manifest) -> str:
    agent = m.principal.get("agent", "agent")
    repo = str(m.task.get("repo", "*"))
    expires = (m.expires_at or "2999-12-31T23:59:59Z").replace("-", "/").replace("T", "T").replace("Z", "Z")

    allow_actions = list(m.tools.get("allow", []))
    deny_patterns = list(m.tools.get("deny", []))

    def json_str(s: str) -> str:
        return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'

    lines = [
        "// Generated by Sentinel Authority - DO NOT HAND EDIT",
        f"// task: {m.task.get('objective')} {repo}",
        "",
        "namespace Sentinel",
        "",
        f"entity Agent;",
        "entity Action;",
        "entity Repository;",
        "",
        f'permit(principal == Agent::"{agent}", action, resource == Repository::"{repo}")',
        "when {",
        "    context.action_name in [" + ", ".join(json_str(a) for a in allow_actions) + "] &&",
        f'    context.time < datetime("{expires}")',
        "};",
        "",
        "// Explicit denies always win over the permit above.",
    ]

    if deny_patterns:
        lines += [
            f"forbid(principal == Agent::\"{agent}\", action, resource)",
            "when {",
            "    context.action_name in [" + ", ".join(json_str(d) for d in deny_patterns) + "]",
            "};",
        ]

    lines += [
        "",
        "// Environment boundary",
        f'forbid(principal == Agent::"{agent}", action, resource)',
        'when { context.environment == "production" };',
        "",
        "// Filesystem / egress boundaries (enforced by the hook/gateway target):",
    ]
    for label, items in (
        ("fs.read", m.filesystem.get("read", [])),
        ("fs.write", m.filesystem.get("write", [])),
        ("fs.deny", m.filesystem.get("deny", [])),
        ("net.allow", m.network.get("allow", [])),
    ):
        for item in items:
            lines.append(f"// {label:<9}: {item}")

    return "\n".join(lines)

