"""Compile an Authority Manifest into an OPA/Rego policy (deny-by-default)."""
from __future__ import annotations

import json

from ..core.evaluator import _glob_to_regex
from ..core.schema import Manifest


def _regexes(patterns: list) -> list:
    return sorted({_glob_to_regex(p.strip().lower()).lstrip("^").rstrip("$") for p in patterns})


def compile_opa(m: Manifest) -> str:
    data = {
        "tool_allow": _regexes(m.tools.get("allow", [])),
        "tool_deny": _regexes(m.tools.get("deny", [])),
        "fs_read": _regexes(m.filesystem.get("read", [])),
        "fs_write": _regexes(m.filesystem.get("write", [])),
        "fs_deny": _regexes(m.filesystem.get("deny", [])),
        "net_allow": _regexes(m.network.get("allow", [])),
        "env_allow": [k for k, v in m.environment.items() if v == "allow"],
        "expires_at": m.expires_at or "2999-01-01T00:00:00Z",
        "delegation_max_depth": int(m.delegation.get("max_depth", 0)),
    }

    return f"""# Generated by Sentinel Authority - DO NOT HAND EDIT
package sentinel.authority

import future.keywords.in
import rego.v1

default allow := false

manifest := {json.dumps(data, indent=2)}

expired if input.now > time.parse_rfc3339_ns(manifest.expires_at)

tool_denied if some d in manifest.tool_deny
tool_denied if regex.match(d, lower(input.action))

tool_allowed if {{
    some d in manifest.tool_allow
    regex.match(d, lower(input.action))
    not tool_denied
}}

path_denied if {{
    some p in manifest.fs_deny
    regex.match(p, path_norm(input.path))
}}

allow if {{
    input.type == "action"
    not expired
    tool_allowed
}}

allow if {{
    input.type == "path"
    not expired
    not path_denied
    input.mode == "r"
    some p in manifest.fs_read
    regex.match(p, path_norm(input.path))
}}

allow if {{
    input.type == "path"
    not expired
    not path_denied
    input.mode == "w"
    some p in manifest.fs_write
    regex.match(p, path_norm(input.path))
}}

allow if {{
    input.type == "host"
    not expired
    some h in manifest.net_allow
    regex.match(h, lower(input.host))
}}

allow if {{
    input.type == "delegate"
    not expired
    input.depth <= manifest.delegation_max_depth
}}

allow if {{
    input.type == "environment"
    not expired
    lower(input.environment) in manifest.env_allow
}}
"""

